output "cluster_id" {
  description = "EKS cluster ID."
  value       = aws_eks_cluster.vgd-cluster.id
}
output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = aws_security_group.vgd-cluster-sg.id
}

output "endpoint" {
  value = aws_eks_cluster.vgd-cluster.endpoint
}
output "cluster_security_group_id_2" {
  description = "Security group ids attached to the cluster control plane."
  value       = aws_eks_cluster.vgd-cluster.vpc_config[0].cluster_security_group_id
}

#output "kubectl_config" {
#  description = "kubectl config as generated by the module."
#  value       = aws_eks_cluster.vgd-cluster.kubeconfig
#}

output "identity" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = aws_eks_cluster.vgd-cluster.identity
}
output "kubeconfig-certificate-authority-data" {
  value = aws_eks_cluster.vgd-cluster.certificate_authority[0].data
}
